services:
  - type: web
    name: who-cares-api
    runtime: python
    rootDir: who_cares_api
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
